[package]
name = "remote_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.69.0"
tflitec = "0.5.1"
byteorder = "1.4.3"
image = "0.24.4"
