[package]
name = "server_side"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.69.0"
byteorder = "1.4.3"
nix = "0.25.0"
libc = "0.2.137"
